connect bancos_bdd/bancos_bdd@cahabdd_s1
DROP TABLE F_CAH_BANCO_1 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_CUENTA_1 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_SUCURSAL_1 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_CUENTA_3 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_EMPLEADO_1 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_MOVIMIENTO_2 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_PAIS_1 CASCADE CONSTRAINTS;
commit;
connect bancos_bdd/bancos_bdd@cahabdd_s2
DROP TABLE F_CAH_BANCO_2 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_CUENTA_2 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_SUCURSAL_2 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_CUENTA_4 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_EMPLEADO_2 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_MOVIMIENTO_1 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_MOVIMIENTO_3 CASCADE CONSTRAINTS;
DROP TABLE F_CAH_PAIS_2 CASCADE CONSTRAINTS;
commit;
exit