--@Autor: Hernández Arrieta Carlos Alberto
--@Fecha creación: 18/Marzo/2019
--@Descripción: Código DDL para el nodo 2

--
-- TABLE: F_CAH_BANCO_2
--

CREATE TABLE F_CAH_BANCO_2(
    BANCO_ID    NUMBER(5, 0)    NOT NULL,
    CLAVE       VARCHAR2(10)    NOT NULL,
    NOMBRE      VARCHAR2(40)    NOT NULL,
    CONSTRAINT F_CAH_BANCO_2_PK PRIMARY KEY (BANCO_ID)
);

--
-- TABLE: F_CAH_CUENTA_2
--

CREATE TABLE F_CAH_CUENTA_2(
    CUENTA_ID    NUMBER(10, 0)    NOT NULL,
    CONTRATO     BLOB             NOT NULL,
    CONSTRAINT F_CAH_CUENTA_2_PK PRIMARY KEY (CUENTA_ID)
);

--
-- TABLE: F_CAH_SUCURSAL_2
--

CREATE TABLE F_CAH_SUCURSAL_2(
    SUCURSAL_ID     NUMBER(10, 0)    NOT NULL,
    NUM_SUCURSAL    NUMBER(3, 0)     NOT NULL,
    BANCO_ID        NUMBER(5, 0)     NOT NULL,
    PAIS_ID         NUMBER(4, 0)     NOT NULL,
    GERENTE_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT F_CAH_SUCURSAL_2_PK PRIMARY KEY (SUCURSAL_ID),
    CONSTRAINT F_CAH_SUCURSAL_2_BANCO_ID_FK FOREIGN KEY (BANCO_ID)
    REFERENCES F_CAH_BANCO_2(BANCO_ID)
);

--
-- TABLE: F_CAH_CUENTA_4
--

CREATE TABLE F_CAH_CUENTA_4(
    CUENTA_ID      NUMBER(10, 0)    NOT NULL,
    NUM_CUENTA     VARCHAR2(18)     NOT NULL,
    TIPO_CUENTA    CHAR(1)          NOT NULL,
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT F_CAH_CUENTA_4_PK PRIMARY KEY (CUENTA_ID),
    CONSTRAINT F_CAH_CUENTA_4_SUCURSAL_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES F_CAH_SUCURSAL_2(SUCURSAL_ID)
);

--
-- TABLE: F_CAH_EMPLEADO_2
--

CREATE TABLE F_CAH_EMPLEADO_2(
    EMPLEADO_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                 VARCHAR2(40)     NOT NULL,
    AP_PATERNO             VARCHAR2(40)     NOT NULL,
    AP_MATERNO             VARCHAR2(40)     NOT NULL,
    FOLIO_CERTIFICACION    VARCHAR2(10),
    JEFE_ID                NUMBER(10, 0),
    CONSTRAINT F_CAH_EMPLEADO_2_PK PRIMARY KEY (EMPLEADO_ID)
);

--
-- TABLE: F_CAH_MOVIMIENTO_1
--

CREATE TABLE F_CAH_MOVIMIENTO_1(
    NUM_MOVIMIENTO      NUMBER(10, 0)     NOT NULL,
    CUENTA_ID           NUMBER(10, 0)     NOT NULL,
    FECHA_MOVIMIENTO    DATE              NOT NULL,
    TIPO_MOVIMIENTO     CHAR(1)           NOT NULL,
    IMPORTE             NUMBER(18, 2)     NOT NULL,
    DESCRIPCION         VARCHAR2(2000)    NOT NULL,
    COMPROBANTE         BLOB,
    CONSTRAINT F_CAH_MOVIMIENTO_1_PK PRIMARY KEY (NUM_MOVIMIENTO, CUENTA_ID),
    CONSTRAINT F_MOVIMIENTO_1_CUENTA_ID_FK FOREIGN KEY (CUENTA_ID)
    REFERENCES F_CAH_CUENTA_2(CUENTA_ID)
);

--
-- TABLE: F_CAH_MOVIMIENTO_3
--

CREATE TABLE F_CAH_MOVIMIENTO_3(
    NUM_MOVIMIENTO      NUMBER(10, 0)     NOT NULL,
    CUENTA_ID           NUMBER(10, 0)     NOT NULL,
    FECHA_MOVIMIENTO    DATE              NOT NULL,
    TIPO_MOVIMIENTO     CHAR(1)           NOT NULL,
    IMPORTE             NUMBER(18, 2)     NOT NULL,
    DESCRIPCION         VARCHAR2(2000)    NOT NULL,
    COMPROBANTE         BLOB,
    CONSTRAINT F_CAH_MOVIMIENTO_3_PK PRIMARY KEY (NUM_MOVIMIENTO, CUENTA_ID),
    CONSTRAINT F_MOVIMIENTO_3_CUENTA_ID_FK FOREIGN KEY (CUENTA_ID)
    REFERENCES F_CAH_CUENTA_4(CUENTA_ID)
);

--
-- TABLE: F_CAH_PAIS_2
--

CREATE TABLE F_CAH_PAIS_2(
    PAIS_ID           NUMBER(4, 0)     NOT NULL,
    CLAVE             VARCHAR2(5)      NOT NULL,
    NOMBRE            VARCHAR2(100)    NOT NULL,
    ZONA_ECONOMICA    CHAR(1)          NOT NULL,
    CONSTRAINT F_CAH_PAIS_2_PK PRIMARY KEY (PAIS_ID)
);

commit;
